.travis.yml
app/scripts/app.js
app/scripts/controllers/about.js
app/scripts/controllers/main.js
bower.json
test/spec/controllers/about.js
test/spec/controllers/main.js

Corrected the name of the AngularJS application to the correct name. Vagrant claimed the name automatically on creation

Corrected "vagrantApp" to "moodCatApp" site wide

---

app/index.html
app/styles/_variables.scss
app/styles/main.scss

Also added vote up, vote down and volume mock buttons

Added some basic menu bar styles

---

app/scripts/controllers/main.js

Make sure to use updateRoomAPI as core branch, because the endpoints have been set correctly there.

Update chat frontend fixes #15

---

app/index.html
app/scripts/controllers/main.js
app/scripts/controllers/moodCatAudio.js

The Core repo you should use is origin/songAPI.

Frontend functions voting fixes #19

---

app/scripts/controllers/main.js
app/styles/main.scss
app/views/moodSelection.html

Transitions into a fitting background when choosing a mood.

Mood background, fixes #7

---

deploy.sh

Added a script to pull the latest version, do a build, copy the right files to dist, and replace the frontend version on the moodcat server with a new one.

Deploy script fixed #72

---

app/mocks/song.json
app/scripts/app.js
app/scripts/controllers/main.js
app/scripts/controllers/moodCatAudio.js
app/views/selectRoom.html
bower.json

It works, but the backend doesn't give a new song.
Tried to fix this in branch next-song, but no succes so far.

Next song fixes #32

---

app/index.html
app/scripts/controllers/classify.js
app/scripts/controllers/main.js
app/scripts/controllers/moodCatAudio.js
app/views/moodSelection.html

Companion for https://github.com/MoodCat/MoodCat.me-Core/pull/142
Fixes https://github.com/MoodCat/MoodCat.me-Frontend/issues/47
* Deduplicated some $http boilerplate code
* Fixed the issue with the non appearing avatar
* Sending the token to the backend so it can authorize users for the chat
Things still to be done (not in this PR)
* Disable/hide form inputs when not authorized. 
* Separate code into different files, possibly theres more room for deduplication

Persistent login, fixes #47

---

app/scripts/controllers/leaderboard.js
app/scripts/controllers/moodCatAudio.js
app/styles/main.scss
app/views/leaderboard.html

Works with leaderboard on the core.
Based on points, instead of master.

Leaderboard fixes #46

---

app/index.html
app/scripts/app.js
app/scripts/controllers/leaderboard.js
app/scripts/controllers/main.js
app/scripts/controllers/moodCatAudio.js
app/scripts/controllers/moodCatUtil.js
app/styles/main.scss
app/views/leaderboard.html
test/karma.conf.js

* Deduplicated code
* Fixed loading of points
* Fixed authentication
* Up to date with https://github.com/MoodCat/MoodCat.me-Core/pull/145

Modifications to points, fixes #45

---

app/views/room.html

Personally like the room centered aligned more.
Note I know this commit / PR should be reapplied to Gijs' refactor branch, but I'm creating an PR so we know that it is fixed, see how it's fixed, can debate on it and do not forget this in the process of merging.

Centered room in the page

---

app/scripts/controllers/leaderboard.js

Polling for points.
Note I know this commit / PR should be reapplied to Gijs' refactor branch, but I'm creating an PR so we know that it is fixed, see how it's fixed, can debate on it and do not forget this in the process of merging.

Implemented points polling

---

app/styles/main.scss
app/views/room.html

Fix some style issues: added some bottom margin to fix mobile view, add padding to progressbar to center it.

Style fixes

---

app/scripts/controllers/moodCatAudio.js

Is compatible with https://github.com/MoodCat/MoodCat.me-Core/pull/156

Makes frontend compatible with backend again.

---

app/scripts/app.js
app/scripts/config.js
app/scripts/controllers/audio/audioController.js
app/scripts/controllers/audio/soundCloudController.js
app/scripts/controllers/classify/classifyController.js
app/scripts/controllers/moodController.js
app/scripts/controllers/points/pointsController.js
app/scripts/controllers/roomController.js
app/scripts/controllers/selectRoomController.js
app/scripts/services/audio/currentSongService.js
app/scripts/services/audio/soundCloudService.js
app/scripts/services/chatService.js
app/scripts/services/classify/classifySongService.js
app/scripts/services/moodService.js
app/scripts/services/points/pointsService.js
app/scripts/services/roomService.js

Made the pull request for Gijs.

Added documentation & fixed a few indentation issues. fixes #61

---

app/index.html
app/scripts/app.js
app/scripts/config.js
app/scripts/services/audio/soundCloudService.js
app/scripts/services/points/pointsService.js
bower.json
test/karma.conf.js

Working on a replacement for the soundcloud API. Still figuring out how to get the correct key from the response.

Own soundcloud api

---

app/scripts/controllers/roomController.js

Fixed message synchronization, don't sync simultanuous on send messag and interval
Fixes #83

Fixed message synchronization,  fixes #83

---

app/index.html
app/scripts/app.js
app/scripts/controllers/moodController.js
app/views/moodSelection.html
app/views/selectRoom.html

Nested ui-views broke the router and some styling, especially the responsive ones.

Fixed nested ui-view

---

app/index.html
app/styles/main.scss

We still have to change the css to actually mark them, but when the state is active, the button gets the `.active` class.

Marking active state in header

---

app/scripts/controllers/audio/audioController.js
app/scripts/controllers/points/pointsController.js
app/scripts/services/classify/classificationService.js

Now we only fetch points right after a login, vote or classification, or every 100 seconds

Fixed excessive point polling

---

app/index.html
app/styles/main.scss

Fixed centering of header timestamp

---

app/views/room.html

Branch name is wrong, wanted to type chatbox.

Disable the ability to make a message when not logged in fixes #111

---

app/styles/main.scss

And increase the chat width for mobile.
Also, the buttons in the navbar in the standard layout were sometimes 1px too high.

Fix responsive navbar

---

app/index.html
app/styles/main.scss
app/views/footer.html

We are not allowed to use soundcloud streaming without a "powered by soundcloud" logo

Added soundcloud image
